default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development: &default
  adapter: postgresql
  encoding: unicode
  database: postgres
  pool: 5
  username: postgres
  password:
  host: db

test:
  <<: *default
  database: test
  username: postgres
  password:

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  password: <%= ENV['CONTACT_TRACKER_DATABASE_PASSWORD'] %>
  pool: 5
