# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27772a5a918ab4f5adc62b0c88731718fb97ebe3f97feaf1b1b445154da839062c425b3e0e023f77dcdf098fd24c72188f5db92821877cb1bece66f525cf1f8c

test:
  secret_key_base: 1d7b3023eef1fb1e7cedc8e0d059f29a9876619dbc109d65c81ffd947186825c76a016a644bd1c4d5462748b4b2a7bddf1dd15020bcf870ffda31b33a20d6d88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
